markdown: rdiscount
pygments: true
permalink: /:categories/:title

home_url: http://joehand.github.com/pdx_ultimate

jspath: http://joehand.github.com/pdx_ultimate/assets/js
csspath: http://joehand.github.com/pdx_ultimate/assets/css
imgpath: http://joehand.github.com/pdx_ultimate/assets/img

name: "Portland Club Ultimate"
author: "Joe Hand"

google_analytics_ID: "UA-20883592-4"

main_color: "148AFF"
main_color_rgb: "0, 34, 68"
background_color: "818A8F"
background_color_rgb: "129, 138, 143"
extra_color: "981E32"
extra_color_rgb: "152, 30, 50"

auto: true
rdiscount:
  extensions: [smart]

best_of_order: [ 1, 2, 3, 4, 5 ]
